import React, { Component } from 'react';
import { BrowserRouter as Router, Route, Link } from 'react-router-dom';
import App from './App';
import {
  Input,
  Header,
  Button,
  Container,
  Dropdown,
  Message,
} from 'semantic-ui-react';
import styled from 'styled-components';

class Howto extends Component {
  constructor(props) {
    super(props);
    this.state = {
      stats: {},
      game_list: [],
      errormessage: '',
      game_selected: 'default',
    };
  }

  async componentDidMount() {}

  componentWillUnmount() {
    console.log('unmounted');
  }

  render() {
    return (
      <div>
        <Container>
          <h1>How to</h1>
          <Header as="h2">Download Scatter</Header>
          <p>
            In order to interact with the EOS blockchain, players will need to
            install scatter wallet. This wallet is available at:{' '}
            <a href="https://get-scatter.com/">https://get-scatter.com/</a>
          </p>
          <Header as="h2">Jungle Testnet</Header>
          <p>
            Current version of BlockCoined is running on{' '}
            <a href="https://jungletestnet.io/">EOS Jungle testnet</a>. To
            create an EOS account on the Jungle Testnet follow the instructions
            on the next section.
          </p>
          <p>
            <div class="media-body">
              <h3 class="title-text">Create an Account</h3>
              <p>
                To create an EOS account on the Jungle TestNet visit{' '}
                <a
                  target="_blank"
                  href="https://monitor.jungletestnet.io/#account"
                >
                  monitor.jungletestnet.io/#account
                </a>{' '}
                and choose a 12 character username. You can generate the EOS key
                pairs{' '}
                <a href="https://nadejde.github.io/eos-token-sale/">here</a>.
                Click on generate EOS key in hyperlink. Save the private and
                public key pair to a text file.
              </p>
            </div>
          </p>
          <Header as="h2">Install Scatter and import private key</Header>
          <p>
            Once Scatter wallet has been installed, it will ask you to create a
            password and seed word. When these steps are complete, player will
            need to import their previously created EOS account into the wallet
            by importing their saved private key. Continue by pressing add key
            button in scatter initial setup.
          </p>
          <p>
            Choose import key when given the option. Select import private key
            as text. Copy previously saved private key from the key pair into
            the text box and press import button. After previous step, scatter
            will take you to a page that allows you to link accounts. Scatter by
            default will only give player the option to use EOS Mainnet. We will
            have to revisit this page once we change the setting of the wallet
            to point to the Jungle Testnet instead of the Mainnet. Press the
            Back button.
          </p>
          <p>
            Click on the gear icon button to get to settings. Click on
            "Networks" on the left side of the setting menu under "Danger Zone"
            Section. By default under "Networks" menu, EOS Mainnet is the only
            option. To add Jungle Testnet into the list of networks by selecting
            "Your Networks" and click on the blue "Add" Button. Fill in the
            following details.
          </p>{' '}
          <p>Blockchain: EOSIO</p>
          <p>Name: JUNGLE</p>
          <p>Host(domain.com or IP): jungle2.cryptolions.io</p>
          <p>Protocol: HTTPS</p>
          <p>Port: 443</p>
          <p>
            Chain ID:
            e70aaab8997e1dfce58fbfac80cbbb8fecec7b99cf982a9444273cbc64c41473
          </p>
          <p>
            Blockcoined currently uses its own in game token. Press Use "Custom
            System Token" button and then fill in the following below:
          </p>
          <p>Contract: blocointoken</p>
          <p>Symbol: BLC</p>
          <p>Decimal: 4</p>
          <p>
            Scroll back up and press "Save" button. After saving, press "back".
            Click below "Search" text box on the key generated by default. The
            name of the key is a bolded variable in the following format
            "Key-xxxxxxxxxx" with x linked accounts below. Select under "Add
            Account" tab and click refresh. Alternatively player can select
            "JUNGLE" under "Link existing EOS account" in the middle dropdown
            menu and then enter previously created account name. Press "Add" to
            add existing linked account. Click on "Linked Accounts" tab to see
            your current account status.
          </p>
          <p>
            Now your account is all set and ready to go. To play the game, you
            will need some in game token, BLC. On the top of this page click on
            Token Fountain and click on "Fill token from blocfountain". This
            will prompt you from Scatter a transaction for claiming token. Allow
            this to fill 100 tokens. This button currently will allow players to
            refill 100 tokens every 120 blocks or 60 seconds. Verify inside
            Scatter wallet that you have recieved 100 BLC tokens.
          </p>
          <Header as="h2">How to play</Header>
          <p>
            Once, you have BLC tokens in your wallet under your account name,
            select BlockCoined on the top right menu.
          </p>
          <p>
            Click on "Join Game" Button. Your EOS Jungle account name is now
            under the bottom of the page in the Player List
          </p>
          <p>
            In order to play, player needs to buy tickets with BLC tokens. Click
            the red button "Send to blockcoined1" to get tickets. By default,
            you will send 10 BLC. 1 BLC token is traded per ticket. Each ticket
            will buy you 1 Queue which is one turn. Once the transaction is
            allowed and completed, you will see the ticket number increase to
            10.
          </p>
          <p>
            To Queue up, press "Buy Queues" button. This will allow player to
            trade 3 Tickets for 3 Queues. Player name will appear in the Queue
            list above. The left top most player is the front of the Queue.
          </p>
          <p>
            Now you are queued up, you are ready to play. When you are at the
            front of the Queue, you will have 60 blocks or 30 seconds to take
            your turn until another player can steal your turn. To execute a
            move, click on a coin and then click on another coin that is the
            closest to swap the coins. For each coin, the closest 4 coins are
            possible moves for swap. Connect three will get you 1 point. Connect
            2 + n will get you n points. All coins are generated randomly by
            hashing blocks number on the blockchain. Whitelist the move in
            Scatter and let Cell_clicked1 and Cell_clicked2 be variables by
            checking these two parameters after whitelsiting in Scatter. This
            will allow Scatter to automatic signatures after each move is
            executed without clicking "Allow" after every move.
          </p>
          <Header as="h2">Refunding and Scoring</Header>
          <p>
            Players except for host can exit game at anytime by clicking the
            "Refund Token" button. Refund in BLC is exactly 1:1 ratio of amount
            of unused Ticket to BLC token.
          </p>
          <p>
            At end of the game, currently after 50 turns, the smart contract on
            EOS blockchain will convert a particular player's score out the sum
            of all player's score as ratio to total number of token funding the
            current game. The formula is as the following: entry.num_ticket +=
            (current_game.Queue_pos_max - 1) * challenger.score /
            current_game.host_score;
          </p>
          <p>
            Ticket tab will update to reflect your winning or losing after smart
            contract refund tickets. When the host close the game, tokens will
            be returned from the hosted game to each EOS player account. Each
            player can only create one game.
          </p>
          <p>
            Write to me @ zhiminzou@gmail.com to submit issues. Currently
            looking for partners to launch this DAPP. No ICO's only free coin
            distributions.
          </p>
          <p />
        </Container>
      </div>
    );
  }
}
export default Howto;
